version: "3.8"  #docker-compose version

services:

  server:
    image: 'nginx:stable-apline'
    ports: 
      - '8000:80'
    volumes:
      -  ./nginx/nginx.conf:/ect/nginx/nginx.conf:ro #configuration file that should be in local file

  php:
    build:      #The build is the image for the container. Context is the folder and dockerfile the file to build container
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    #ports:
    #  - '3000:9000'  #mapping 3000 (host machine) to 9000 (container internal port)
                    #But will be commented because will change in conf nginx to 9000. the comunication 
                    #are between containers, not with local host

  mysql:
    image: 'mysql:5.7'
    env_file:   #environment file with variable. might be sensitive, so add thi file to gitignore 
      - ./env/mysql.env

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  #artisan:

  #npm: